### ISSUE TITLE
Rename "output_names" argument

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audonnx#26]
I'm always having troubles to remember "output_names" in `Model.__call__()`, and I also find it a bit long:

![image](https://user-images.githubusercontent.com/10383417/172666896-1d73e9e0-2a77-49d6-a601-55cfc2ac1840.png)

So I wonder if we should deprecate it and find a name that is easier to remember. Maybe "nodes"? Or "outputs" to fit `Model.outputs`?

**Comment by hagenw** [comment]
I agree and would vote for `outputs` as it is easier to understand if you are new to ONNX than `nodes`.
As we have used the package now at several places, I would also vote for adding a relative high version (e.g. 1.2) to the deprecation warning.
