### ISSUE TITLE
Limit number of used threads when model is run on CPU

### ISSUE THREAD

**Issue by hagenw** [audeering/audonnx#80]
When loading a model on the CPU and running it, onnxruntime will use as many resources as it can get.
This can be avoided by specifying `intra_op_num_threads` and `inter_op_num_threads`.

Maybe we can tackle both by adding an `num_workers` argument to `audonnx.load()` and `audonnx.Model` as we have in other packages?
It seems also reasonable to set the default to 1.

**Comment by audeerington** [comment]
Agreed. I would also keep (and explain) the option of letting onnxruntime choose, which could also be set with `num_workers=0` .

**Comment by hagenw** [comment]
In `audinterface` we have implemented this with `None`:

![image](https://github.com/audeering/audonnx/assets/173624/10f49076-6327-406a-ae1c-da595635b982)

E.g. https://audeering.github.io/audinterface/api/audinterface.Process.html
